crossplane/org

.github/ISSUE_TEMPLATE/new-member.md, config/members-crossplane.yaml, processes/new-member.md
Adds documentation and an issue template for adding new members to the Crossplane org. Also introduces `Membership` manifests that will be reconciled by `provider-github`. You can see this in action on recent [CrossHack stream](https://youtu.be/osrUo-7Twz0) -- note that this is not enabled yet, this is just adding the manifests so we can start adding new members to the org via this process (+ the current manual step) while the org cluster is being set up.
Also note that the manifests contain only 24/40 members because some members have chosen to mark their membership as private. This is fine from a reconciliation perspective because provider-github will have credentials to view the private members, but out of an abundance of caution I didn't want to reflect those private members in this …
=> Add documentation and manifests for adding new org members

config/members-crossplane.yaml
Adds @rahulgrover99 as a new member in the Crossplane org.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
Fixes #4 
@jbw976 since the org cluster is not setup yet, we'll still need you to manually add @rahulgrover99.
=> Add rahulgrover99 as new member

config/members-crossplane.yaml
Adds @ulucinar to crossplane org as a regular member.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
Fixes #6 
/cc @jbw976
=> Add ulucinar as crossplane org member

config/members-crossplane.yaml
This PR adds https://github.com/zzxwill as a member of the Crossplane org.
The tracking issue for membership is https://github.com/crossplane/org/issues/10, following the new member process in https://github.com/crossplane/org/blob/main/processes/new-member.md.
=> add zzxwill as member

config/members-crossplane.yaml
This PR adds @tnthornton as a member to the crossplane org.
Fixes #12,  following the new member process in https://github.com/crossplane/org/blob/main/processes/new-member.md.
=> add tnthornton as a member

config/members-crossplane.yaml
This PR adds @luebken as a member to the crossplane organization.  He will be driving a lot of project planning and coordination for upcoming Crossplane milestones.  Thanks @luebken!
Fixes #14
=> add luebken as member

config/members-crossplane.yaml
This PR adds @sergenyalcin as a Crossplane organization member.
Fixes #22 
User ID obtained from https://api.github.com/users/sergenyalcin.
=> add sergenyalcin as member

config/members-crossplane.yaml
Fixes https://github.com/crossplane/org/issues/24
@negz could you add him as member in the UI and drop the `inviteeId` here?
=> add stevendborelli

config/members-crossplane.yaml
This PR adds @ezgidemirel to the Crossplane org membership list, as per #28 
Github user ID obtained from https://api.github.com/users/ezgidemirel
Fixes #28
=> add ezgidemirel

config/members-crossplane.yaml
This PR adds https://github.com/ytsarev and https://github.com/mcbenjemaa as members to the Crossplane org.
Fixes #30 and #27
User IDs obtained from https://api.github.com/users/ytsarev and https://api.github.com/users/mcbenjemaa
=> Add ytsarev and mcbenjemaa as members

config/members-crossplane.yaml
This PR adds @Ruhika1417 as a member of the Crossplane organization, as per the request in #33.
User data retrieved from https://api.github.com/users/Ruhika1417.
=> Add Ruhika1417 to org membership

config/members-crossplane.yaml
This PR adds the following contributors as new members in the Crossplane org:
* @parul5sahoo
* @avalanche123
Fixes #35 and #36
Member IDs obtained from https://api.github.com/users/parul5sahoo and https://api.github.com/users/avalanche123.
=> add @parul5sahoo and @avalanche123 as Crossplane org members

config/members-crossplane.yaml
This PR adds multiple new members to the Crossplane org, tracked by the following issues:
* #38 
* #39 
* #40 
* #41 
* #42 
Github user IDs were obtained from:
* https://api.github.com/users/bobh66
* https://api.github.com/users/jastang
* https://api.github.com/users/kiote
* https://api.github.com/users/nullable-eth
* https://api.github.com/users/nlinx
=> Add new crossplane org members: bobh66, jastang, kiote, nlinx, nullable-eth

config/members-crossplane.yaml
This PR adds a batch of new Crossplane org members, tracked by the following issues:
* #44 
* #46 
* #48 
* #49 
* #50 
All members have been ack'd by their sponsors.  The data for github user ID was taken from the following pages:
* https://api.github.com/users/iAnomaly
* https://api.github.com/users/tanujd11
* https://api.github.com/users/epk
* https://api.github.com/users/piotr1215
* https://api.github.com/users/AlainRoy
=> Add crossplane org members iAnomaly, tanujd11, epk, Piotr1215, AlainRoy

config/members-crossplane.yaml
This PR adds @plumbis as an org member.  Github user id obtained from https://api.github.com/users/plumbis.
Fixes #52
=> add plumbis as org member

config/members-crossplane.yaml
This PR adds @jeanduplessis as a member, fixes #55 
Github user ID obtained from https://api.github.com/users/jeanduplessis
=> Add @jeanduplessis as a member

config/members-crossplane.yaml
This PR adds @phisco as a member of the crossplane org.
Fixes #57 
Github user ID obtained from https://api.github.com/users/phisco.
=> add phisco as member

config/members-crossplane.yaml
This PR adds @lsviben as a member to the Crossplane org.
Fixes #59 
User ID retrieved from https://api.github.com/users/lsviben
=> Add lsviben to members

config/members-crossplane.yaml
This PR adds @elohmrow as a member to the crossplane org.
Github user ID was obtained from https://api.github.com/users/elohmrow
Fixes #54
=> Add elohmrow as member

config/members-crossplane.yaml
Adds @gberche-orange and @sttts as members of the Crossplane organization.
Member IDs obtained from https://api.github.com/users/gberche-orange and https://api.github.com/users/sttts.
Fixes #64 #65
=> Add gberche-orange and sttts as members

config/members-crossplane.yaml
This PR adds @smileisak as a member to the Crossplane organization.
User ID obtained from https://api.github.com/users/smileisak
Fixes: #71
=> Add smileisak to org as member

config/members-crossplane.yaml
This PR adds @abelhoula to the list of Crossplane members. Member ID obtained from:
https://api.github.com/users/abelhoula
Fixes #75
=> add abelhoula to members

config/members-crossplane.yaml
This PR adds @tr0njavolta to the Crossplane members list.
Member ID retrieved from https://api.github.com/users/tr0njavolta.
Fixes #77
=> add tr0njavolta to members

config/members-crossplane.yaml
This PR adds @enesonus as a member to the Crossplane organization.
Member ID was retrieved from https://api.github.com/users/enesonus.
Fixes https://github.com/crossplane/org/issues/79
=> add enesonus to members

config/members-crossplane.yaml
This PR adds @markandersontrocme to the Crossplane org members.
Github user ID obtained from https://api.github.com/users/markandersontrocme
Fixes #82
=> add markandersontrocme to members

config/members-crossplane.yaml
This PR adds https://github.com/erhancagirici as a member to the Crossplane org. Member ID obtained from https://api.github.com/users/erhancagirici.
Fixes #95
=> add erhancagirici as member

config/members-crossplane.yaml
This PR adds @gaiters-cafes as a member in the Crossplane organization.  Member ID obtained from https://api.github.com/users/gaiters-cafes.
Fixes #97
=> add gaiters-cafes as member
